FROM adoptopenjdk/openjdk11:latest
ADD build/libs/electricity-bill-payment-system-0.0.1-SNAPSHOT.jar electricity-bill-payment-system-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java","-jar","electricity-bill-payment-system-0.0.1-SNAPSHOT.jar" ]